ServiceSub/ServiceSub/Models/Administrator.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace ServiceSub.Models
{
    public class Administrator
    {
        [Required]
        [Display(Name = "Login")]
        public string UserName { get; set; }

        [Required]
        [DataType(DataType.Password)]
        [Display(Name = "Hasło")]
        public string Password { get; set; }

        [Display(Name = "Zapamiętaj mnie")]
        public bool RememberMe { get; set; }
    }
}

ServiceSub/ServiceSub/Controllers/AdministratorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ServiceSub.Models;
using System.Data.Entity;

namespace ServiceSub.Controllers
{
    [Authorize]
    [AllowAnonymous]
    public class AdministratorController : Controller
    {     
        public ActionResult Login()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Login(Users u)
        {
            // section for post login
            if (ModelState.IsValid)
            {
                using (ServiceSubEntities dc = new ServiceSubEntities())
                {
                    var local = dc.Users.Where(a => a.userName.Equals(u.userName) && a.password.Equals(u.password)).FirstOrDefault();

                    if (local != null)
                    {
                        Session["LogedUserID"] = local.Id.ToString();
                        Session["LogedUserFullName"] = local.FullName.ToString();
                        return RedirectToAction("AfterLogin");
                    }
                }
            }
            return View("BadLogin");
        }

        public ActionResult AfterLogin()
        {
            if (Session["LogedUserID"] != null)
            {               
                return RedirectToAction("AdminIndex");
            }
            else
            {
                return RedirectToAction("Index");
            }
        }

        public ActionResult AdminIndex()
        {
            return View();
        }
    }
}

ServiceSub/ServiceSub/Views/Administrator/AdminIndex.cshtml
@{
    ViewBag.Title = "AdminIndex";
}

<h2>Witamy</h2>
<h2>Wybierz opcje:</h2>

<p>
    <a href="/Newsletter/Send">Wyślij newsletter</a>
</p>
<p>
    <a href="/Subscriber/Subscribe">Dodaj subskrypcje</a>
</p>
<p>
    <a href="/Subscriber/Unsubscribe">Usuń subskrypcje</a>
</p>
<p>
    <a href="/Subscriber/List">Lista subskrypcji</a>
</p>

ServiceSub/ServiceSub/Views/Administrator/AfterLogin.cshtml
@{
    ViewBag.Title = "Zalogowano pomyślnie";
}

<h2>Zalogowano pomyślnie</h2>

@if(Session["LogedUserFullName"] != null)
{
    <text>
        Witaj @Session["LogedUserFullName"].ToString() w serwisie Subskrypcja.
        <br />
        <p>
            Za chwile zostaniesz przekierowany do Panelu właściwego...
        </p>
    </text>
}

ServiceSub/ServiceSub/Views/Administrator/BadLogin.cshtml
@{
    ViewBag.Title = "Zły login";
}

<h2>Zły login</h2>

<p> Wprowadzone przez Ciebie dane są niepoprawne. Spróbuj ponownie</p>

<div>
    @Html.ActionLink("Zaloguj", "Login", "Administrator")   
</div>

ServiceSub/ServiceSub/Views/Administrator/Login.cshtml
@model ServiceSub.Models.Administrator

@{
    ViewBag.Title = "Logowanie do serwisu";
}

<h2>Zaloguj się do serwisu Subskrypcja</h2>

@using (Html.BeginForm("Login", "Administrator", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    if(ViewBag.Message != null)
    {
        <div style="border:1px solid red">
            @ViewBag.Message
        </div>
    }
    <table>
        <tr>
            <td>@Html.LabelFor(a => a.UserName)</td>
            <td>@Html.TextBoxFor(a => a.UserName)</td>
            <td>@Html.ValidationMessageFor(a => a.UserName)</td>
        </tr>
        <tr>
            <td>@Html.LabelFor(a => a.Password)</td>
            <td>@Html.TextBoxFor(a => a.Password)</td>
            <td>@Html.ValidationMessageFor(a => a.Password)</td>
        </tr>
        <tr>
            <td></td>
            <td>
                <input type="submit" value="Zaloguj"/>
            </td>
            <td></td>
        </tr>
    </table>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    }